### ISSUE TITLE
Prymcoin

### ISSUE THREAD

**Issue by willaimswalla** [DivvySD/dashboard#17] opened 2022-04-09 18:50 UTC
### Contract Address

0x439D7800041f0C09f144855344F9c74377DBb4B5

### Project Name

Prymcoin

### Token Symbol

SPC

### Custom Color

#ffab40

### Interested in Divvy Locker and Lava Flow?

- [x] Yes

**Comment by CryptoJoshua** [comment] 2022-04-09 19:17
Duplicate of #16

**Closed as completed by CryptoJoshua** 2022-04-09 19:17 UTC
Labels: listing
